# Generated by Django 4.2 on 2023-04-05 11:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=30)),
                ('yosh', models.SmallIntegerField()),
                ('ish_vaqti', models.DateTimeField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Haydovchi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=30)),
                ('tel', models.CharField(max_length=15)),
                ('kiritilgan_sana', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Suv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brend', models.CharField(max_length=30)),
                ('narx', models.IntegerField()),
                ('litr', models.CharField(max_length=10)),
                ('batafsil', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Mijoz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=30)),
                ('tel', models.CharField(max_length=15)),
                ('manzil', models.CharField(max_length=50)),
                ('qarz', models.IntegerField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Buyurtma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyurtma_vaqti', models.DateTimeField()),
                ('buyurtma_miqdori', models.SmallIntegerField()),
                ('umumiy_summa', models.IntegerField()),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Asosiy.admin')),
                ('haydovchi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Asosiy.haydovchi')),
                ('mijoz', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Asosiy.mijoz')),
                ('suv', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Asosiy.suv')),
            ],
        ),
    ]
